/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface activitiesEntity {
  'created_at'?: Date;
  'description': string;
  'id'?: number;
  'leader_id': string;
  'maybe_end_at': Date;
  'name': string;
  'started_at': Date;
  'status_id': number;
  'type_id': number;
  'updated_at'?: Date;
  'xp': number;
}
export interface authenticationEntity {
  'cpf': string;
  'email': string;
  'id'?: number;
  'password': string;
  'user_id': string;
  'username': string;
}
export interface knex_migrationsEntity {
  'batch'?: number | null;
  'id'?: number;
  'migration_time'?: Date | null;
  'name'?: string | null;
}
export interface knex_migrations_lockEntity {
  'index'?: number;
  'is_locked'?: number | null;
}
export interface member_activityEntity {
  'activity_id': number;
  'id'?: number;
  'member_id': string;
}
export interface member_roleEntity {
  'id'?: number;
  'member_id': string;
  'role_id': number;
}
export interface member_techEntity {
  'id'?: number;
  'member_id': string;
  'tech_id': number;
}
export interface membersEntity {
  'born_at'?: Date | null;
  'created_at'?: Date | null;
  'description'?: string | null;
  'fullname': string;
  'gender'?: string | null;
  'id'?: string;
  'started_course_at': Date;
  'updated_at'?: Date | null;
}
export interface projectsEntity {
  'activity_id': number;
  'id'?: number;
  'pdf_url'?: string | null;
  'repository_url': string;
}
export interface rolesEntity {
  'created_at'?: Date | null;
  'id'?: number;
  'name': string;
}
export interface status_activitiesEntity {
  'created_at'?: Date | null;
  'id'?: number;
  'name': string;
}
export interface tb_testEntity {
  'body': string;
  'created_at'?: Date;
  'id'?: number;
  'updated_at'?: Date;
}
export interface techsEntity {
  'created_at'?: Date | null;
  'id'?: number;
  'name': string;
}
export interface types_activitiesEntity {
  'created_at'?: Date | null;
  'id'?: number;
  'name': string;
}
